apiVersion: v1
kind: Secret
metadata:
  name: more-munch-secrets
type: Opaque
stringData:
  DATABASE_URL: "file:./data/more-munch.db"
  SEED_API_KEY: "changeme"
  KAKAO_REST_API_KEY: "changeme"
  NAVER_CLIENT_ID: "changeme"
  NAVER_CLIENT_SECRET: "changeme"
